### ISSUE TITLE
Creations disappear sometimes

### ISSUE THREAD

**Issue by flatsiedatsie** [bewee/macrozilla#10] opened 2020-10-01 12:43 UTC
It seems on some clicks the UI thinks the creation needs to put back in the sidebar.

![macros-addon-disappearing](https://user-images.githubusercontent.com/805405/94782194-2a6d9080-03cb-11eb-8c1c-5089d8079b92.gif)

Should the sidebar actually be able to contain elements that have been (partially) filled in? Shouldn't it only be able to hold basic building blocks?

**Comment by Galveston01** [comment] 2020-10-01 16:25
> It seems on some clicks the UI thinks the creation needs to put back in the sidebar.

That's weird... Does this happen in a predictable way or rather by chance? I tried to reproduce it but was unable. If it is the former, could you please give me step-by-step instructions on how to reproduce this problem?

> Shouldn't it only be able to hold basic building blocks?

You're absolutely right about that. Since I wasn't able to reproduce this problem either, could you please as well describe to me how to reproduce this problem?

**Comment by Galveston01** [comment] 2020-10-11 19:45
Hi @flatsiedatsie,

Could you please check whether the described problems still occur in the newest release, which is now available through the add-on list?

Regards :)

**Comment by flatsiedatsie** [comment] 2020-11-02 14:35
I think that bug is fixed. But clicking in the UI is still very.. dangerous. Here I am just clicking on things:

![macrozilla](https://user-images.githubusercontent.com/805405/97880092-0500d900-1d21-11eb-8088-17c002c11fc3.gif)

Luckily I can go back and choose "do not save changes".

**Comment by bewee** [comment] 2020-11-02 19:48
Hi @flatsiedatsie,

Thanks a lot for your feedback. The reason why this feels so unnutural is most likely because clicking an element begins dragging it from its center, thereby moving it. I opened a new issue (#28) and will have a look at this later.

Regards :)

**Closed by bewee** 2020-11-02 19:48 UTC
Labels: bug
